export default {
  NEW_PARTICIPATION: "NEW_PARTICIPATION",
  PARTICIPATION_ACCEPTED: "PARTICIPATION_ACCEPTED",
  PARTICIPATION_REFUSED: "PARTICIPATION_REFUSED",
  PARTICIPATION_CANCELED: "PARTICIPATION_CANCELED",
};
