name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install global packages
        uses: bahmutov/npm-install@v1.7.4

      - name: Install api packages
        uses: bahmutov/npm-install@v1.7.4
        with:
          working-directory: api

      - name: Install client packages
        uses: bahmutov/npm-install@v1.7.4
        with:
          working-directory: client

      - name: Run tests
        run: npm run unit-tests
